### PR TITLE
disable the eneco vpn in inittab

### PR DESCRIPTION
**Pull request by IgorYbema**
Need to disable VPN in inittab as this helps preventing automated libc6 (firmware 5.0.4) installation when users are trying to install packages which depend on glibc/libc6

### CODE REVIEW

**Comment by IgorYbema** [comment]
Really need this to be in the payload also. Yet another user bricked his toon after succesfully rooting the toon but after that using a busybox package with glibc/libc6 depency and a running VPN causing the wrong (5.0.4) libc6 to be installed. https://www.domoticaforum.eu/viewtopic.php?f=101&t=11999&start=240#p89702

**Comment by martenjacobs** [comment]
wish we didn't have to do this, but oh well...

**Comment by IgorYbema** [comment]
Oops..  this pull request also took another commit with it I just was working on (uboot-only, just like boot-only). Maybe you want to check this. I am now also pull requesting for readme and __main__.py

**Comment by martenjacobs** [comment]
I saw that and thought you meant for that to happen :P
I think it looks pretty good, I see no reason to revert at the moment.

**Pull request merged**
